### ISSUE TITLE
Provide info on job params in YAML

### ISSUE THREAD

**Issue by atomashpolskiy** [bootique/bootique-job#28]
Need API to retrieve job parameters from YAML config (in some sense they are perceived as "default" by users).

**Comment by atomashpolskiy** [comment]
In fact, for `SingleJob` the best way would be to replace
```
public JobMetadata getMetadata() {
    return delegate.getMetadata();
}
```
with
```
public JobMetadata getMetadata() {
    return merge(execution.getParams(), delegate.getMetadata());
}
```

**Comment by andrus** [comment]
This seems to muddle the distinction between job singleton parameters and parameters of a given job run. Whether this is important or not, I have no idea yet.

**Comment by andrus** [comment]
After discussing offline, it actually makes sense, as "execution" is simply a param set.

**Comment by andrus** [comment]
While this issue is still something that we will need to address, it begs a bigger question on the distinction between a job and an execution, and will probably result in refactoring `Job` API (e.g. base metadata can be gathered from annotations, while execution metadata may be passed to the "run" method). So closing this task, as we won't be implementing it as described.
